baseurl = "/"
languageCode = "pt-br"
title = "@NathPaiva"
theme = "nath-theme"

[menu]
    [[menu.main]]
        name = "About"
        pre = "<i class='fa fa-user fa-fw'></i>"
        weight = 0
        identifier = "about"
        url = "/about/"
    [[menu.main]]
        name = "Getting started"
        pre = "<i class='fa fa-road'></i>"
        weight = 1
        url = "/getting-started/"
